### ISSUE TITLE
Golden Files won't update until failed test is run.

### ISSUE THREAD

**Issue by Jagl257** [stackbuilders/hspec-golden#12]
In order to update the `golden` files, a failed test must be run first to override the `actual` file. Only then the CLI will update the golden file.

**Comment by CristhianMotoche** [comment]
Hi @Jagl257  Yeah, the CLI's purpose is to only update the golden files now. I'm not sure if there's a way to run the tests using `hspec` CLI via a second CLI (in this case `hgold`). I'll try to research a little bit about it. Feel free to open a PR if you want to work on this.

**Comment by CristhianMotoche** [comment]
Hey @Jagl257 I'll be closing this issue for now since it's necessary to run the tests to know if `actual` value changed or not. The CLI can be used after that to update the golden files.
