### ISSUE TITLE
Allow first execution to count as a test failure

### ISSUE THREAD

**Issue by ChickenProp** [stackbuilders/hspec-golden#16]
When I'm running golden tests in CI, I'd like to ensure that the expected output has been added to the repository. It seems like the natural way to do that is to mark the tests as failed on first execution.

I can probably make a PR if you'd be happy to accept this. By default I'd add a record field `failFirstTime :: Bool` to `Golden` (set to `False` in `defaultGolden`), and replace the `GoldenResult` constructor `SameOutput` with `SameOutputSucceed` and `SameOutputFail`.

**Comment by CristhianMotoche** [comment]
Thank you so much for your contribution @ChickenProp
