### ISSUE TITLE
Allow `hgold` to run recursively

### ISSUE THREAD

**Issue by ChickenProp** [stackbuilders/hspec-golden#17]
There's nothing to stop a test name from having a "/" in it, and (at least on linux) that creates nested directories inside `goldenTestDir`. (I guess you'd run into problems if you had a test named "foo/golden" or "foo/actual" along with one named "foo".) But `hgold` only looks one level deep. It's easy enough to do `for d in .golden/**/; do hgold -u "$d"; done`. But would it be okay to make `hgold` run recursively, to avoid needing that?

If yes, I can probably make a PR for it.

**Comment by ChickenProp** [comment]
Sure thing. For what it's worth, I quite like that nested directories are allowed - I've been deliberately using them to group together tests. Escaping / to have a flat directory wouldn't cause problems, it would just make the directory slightly messier.

**Comment by CristhianMotoche** [comment]
Hi @ChickenProp I think we can update the `hgold` CLI. Feel free to make a PR for this. Thanks you so much!

**Comment by CristhianMotoche** [comment]
Thank you so much for your contribution @ChickenProp
