### ISSUE TITLE
Setting to add a custom file extension to "actual" and "golden" files

### ISSUE THREAD

**Issue by bitc** [stackbuilders/hspec-golden#23]
It would be helpful if there was a `fileExtension :: String` setting inside `Golden`. For example "png" or "html". 

This way the files would be named "actual.png" and "golden.png" and it would make it possible to directly view the files by double clicking them, and also would make the contents of the files clearer.

Thank you

**Comment by CristhianMotoche** [comment]
Thanks for the suggestion @bitc Sounds good to me, but I'm busy this week and I won't be able to do it right now. Nevertheless, feel free to open a PR if you want to work on it. :slightly_smiling_face:
