### ISSUE TITLE
Licensing clarification

### ISSUE THREAD

**Issue by SDR92** [stackbuilders/hspec-golden#34]
For the tag version v0.2.0.0 in the License file there is a BSD 3 Clause text, but all over the component we can find only MIT License references. I understood that for the master version you changed that text with the MIT License one, but for that specific version should we consider that BSD 3 Clause license or it was a mistake and the main license is actually MIT License?

**Comment by CristhianMotoche** [comment]
Hello @SDR92 Thanks for reporting this. I think it was a mistake. It should be a MIT License as it's now shown in [the License file](https://github.com/stackbuilders/hspec-golden/blob/7cab5f94c65fcb9c2a6044a2a2f4b9d9711968fd/LICENSE#L1), [the package definition](https://github.com/stackbuilders/hspec-golden/blob/cbf5e7e1399a35fe101d7f42e3edbcca63ac50d5/package.yaml#L4), and the [source code](https://github.com/stackbuilders/hspec-golden/blob/4b0ad56b2de0254a7b1e0feda917656f78a5bcda/src/Test/Hspec/Golden.hs#L5).
