### ISSUE TITLE
Look up for a way to get the information from the test description to name the snapshot

### ISSUE THREAD

**Issue by CristhianMotoche** [stackbuilders/hspec-golden#43]
In order to stop requesting the users for a name for the golden files, it would be great to get that information from the test itself. I already requested some information about it in the [hspec](https://github.com/hspec/hspec/issues/855) repository. My goal is to make the golden test need less config and maybe at some point have more cool features related to snapshot testing like the ones from [Jest](https://jestjs.io/es-ES/docs/snapshot-testing).

**Comment by sol** [comment]
> In order to stop requesting the users for a name for the golden files, it would be great to get that information from the test itself. I already requested some information about it in the [hspec](https://github.com/hspec/hspec/issues/855) repository. My goal is to make the golden test need less config and maybe at some point have more cool features related to snapshot testing like the ones from [Jest](https://jestjs.io/es-ES/docs/snapshot-testing).

I think this can be implemented without any changes to a Hspec. Try something along the lines of:

```haskell
golden :: String -> IO String -> Spec
golden description action = do
  path <- (++ [description]) <$> getSpecDescriptionPath
  it description $ do
    action >>= defaultGolden (intercalate '-' path)
```

**Comment by CristhianMotoche** [comment]
Indeed, that seems like a very easy approach. Thanks a lot @sol !
