### ISSUE TITLE
Create a helper that uses the test description for the golden file

### ISSUE THREAD

**Issue by CristhianMotoche** [stackbuilders/hspec-golden#44]
The golden file name is required in the `d` function. Let's create a helper that users the test description to name the golden test [as suggested in this issue](https://github.com/stackbuilders/hspec-golden/issues/43#issuecomment-1704058107). The helper needs to meet the following criteria:

1. Make the test readable:

```hs
describe "my golden suite" $
  golden "hello world" $ do
     let output =  "MY OUTPUT"
     runGolden output
```

2. `golden` will replace `it` (from hspec) and `runGolden` will replace `defaultGolden`
3. If there are multiple `runGolden` in a `golden` suite the last one will be taken (this could change in the future)

**Comment by FranzGB** [comment]
Can we close this issue now @CristhianMotoche ?

**Comment by CristhianMotoche** [comment]
Yes we can! Thanks @FranzGB
